### ISSUE TITLE
Wolfictl does not understand vars in expected-sha lines in pipelines 

### ISSUE THREAD

**Issue by strongjz** [wolfi-dev/wolfictl#288]
woflictl doesnt understand the melange vars, here;'s an example of a ci failure https://github.com/wolfi-dev/os/pull/3335/checks#step:4:9  one line in question https://github.com/wolfi-dev/os/pull/3335/files#diff-433c67391bb6d11409699d4634e68ebd1d199daf95eaf43b0fc745f3a6014927R141

**Comment by deitch** [comment]
These links are really helpful. You _must_ want this to get fixed if you give precise pointers to the issue and the source that drove it. 😄

**Comment by deitch** [comment]
if nothing else, at least I didn't break this in bringing in the DAG 😆

**Comment by strongjz** [comment]
working in open source I feel that I have learned how to ask a precise question

**Comment by deitch** [comment]
Melange is the one that normally parses the vars. I will see if it has a library surface that we can bring in to do this, or if it is simple, replicate it.

**Comment by deitch** [comment]
> I have learned how to ask a precise question

Oh yeah! I have gotten pretty good at making my questions precise and include good reproducible examples. Brief? Not so much. You win the prize there.

**Comment by deitch** [comment]
This gets stranger. It looks like wolfictl _is_ calling `melange.ReadAllPackagesFromRepo()`, which eventually wraps `ParseConfiguration()` which does the var interpolation. Will keep digging.

**Comment by deitch** [comment]
Got somewhere. The interpolation of variables actually takes place in two different places in two different stages.

## Where interpolation happens

### `ParseConfiguration`

[ParseConfiguration](https://github.com/chainguard-dev/melange/blob/f6926b40d826320127b2ad941d04619d15b9854a/pkg/build/build.go#L947): this does, indeed, read the `Vars` and load them into `cfg.Vars`, then [uses that to create a `configMap` and from there a `replacer`](https://github.com/chainguard-dev/melange/blob/f6926b40d826320127b2ad941d04619d15b9854a/pkg/build/build.go#L1118-L1119).

It then uses that `replace` _only_ to [update the package name/version/description](https://github.com/chainguard-dev/melange/blob/f6926b40d826320127b2ad941d04619d15b9854a/pkg/build/build.go#L1121-L1123).

`ParseConfiguration` thus leaves most vars in their raw state, in your example:

```
map[string]string [
        "uri": "https://nginx.org/download/nginx-${{vars.NGINX_VERSION}}.tar.gz", 
        "expected-sha256": "${{vars.NGINX_SHA}}", 
        "strip-components": "0", 
]
```

### Pipeline

The rest of the interpolation happens only [during melange's pipeline execution](https://github.com/chainguard-dev/melange/blob/f6926b40d826320127b2ad941d04619d15b9854a/pkg/build/pipeline.go#L109-L117).

## How to resolve this

So wolfictl calls `ParseConfiguration`, and gets back a `build.Configuration` properly rendered by melange, but the variable rendering in pipelines doesn't happen until later.

We have a few possibilities.

* Have `ParseConfiguration()` do a full interpolation. I suspect that there may be a reason we do not do this earlier, if some vars can be set over time? I don't think so, but @kaniini would know.
* Have a separate command like `build.Configuration.Interpolate(map[string]string)` which would use the existing config, parameters, and interpolate everything. This probably wouldn't be used by melange, but maybe in the future.
* Reproduce the logic to do the above inside wolfictl

I dislike the last one. If we are confident that vars really do not change throughout execution, and only that the second stage (during pipelines) was selected because it was convenient, then that would make sense. Otherwise, we probably should do the middle option.

Thoughts?
